<?php

namespace BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FavoritesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoritesRepository extends EntityRepository
{
}
